"use client";

import { useState, useEffect } from 'react';
import { Settings as SettingsIcon, Mail, CheckCircle, XCircle, Loader2, Send, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { useAuth } from '@/contexts/auth-context';
import { authService } from '@/lib/api/services/auth.service';
import { toast } from 'sonner';

/**
 * Indique si l'email est auto-généré (cas des comptes inscrits par
 * wallet : format `wallet_<adresse>@timelock.local`). Sert à masquer
 * le faux email dans l'UI et à proposer à la place « Ajouter un email ».
 */
const isAutoGeneratedEmail = (email: string | null | undefined): boolean => {
  if (!email) return true;
  return email.includes('@timelock.local') || email.startsWith('wallet_');
};

export default function SettingsPage() {
  const { user } = useAuth();
  const [email, setEmail] = useState('');
  const [isEmailVerified, setIsEmailVerified] = useState(false);
  const [isSendingVerification, setIsSendingVerification] = useState(false);
  const [isLoadingStatus, setIsLoadingStatus] = useState(true);

  // Distingue les comptes email/mdp (vrai email) des comptes wallet
  // (email auto-généré) — toute la branche « Changer le mdp » + « Vérifier
  // l'email » dépend de ça.
  const hasRealEmail = user?.email && !isAutoGeneratedEmail(user.email);

  useEffect(() => {
    if (user) {
      // Pour les comptes wallet, on ne pré-remplit pas le champ avec le
      // faux email auto-généré (sinon l'utilisateur le verrait apparaître
      // comme « son » email).
      setEmail(hasRealEmail ? user.email : '');
      loadVerificationStatus();
    }
  }, [user, hasRealEmail]);

  const loadVerificationStatus = async () => {
    try {
      const status = await authService.getVerificationStatus();
      setIsEmailVerified(status.isVerified);
    } catch (error) {
      console.error('Error loading verification status:', error);
    } finally {
      setIsLoadingStatus(false);
    }
  };

  const handleSendVerification = async () => {
    setIsSendingVerification(true);
    try {
      await authService.sendVerificationEmail();
      toast.success('Email de verification envoye !');
    } catch (error: any) {
      toast.error(error.response?.data?.message || 'Erreur lors de l\'envoi');
    } finally {
      setIsSendingVerification(false);
    }
  };
  const [oldPassword, setOldPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isChangingPassword, setIsChangingPassword] = useState(false);

  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!oldPassword || !newPassword) {
      toast.error('Remplis tous les champs');
      return;
    }
    if (newPassword.length < 8) {
      toast.error('Le nouveau mot de passe doit faire au moins 8 caractères');
      return;
    }
    if (newPassword !== confirmPassword) {
      toast.error('Les mots de passe ne correspondent pas');
      return;
    }
    if (newPassword === oldPassword) {
      toast.error("Le nouveau mot de passe doit être différent de l'ancien");
      return;
    }

    setIsChangingPassword(true);
    try {
      await authService.changePassword(oldPassword, newPassword);
      toast.success('Mot de passe changé avec succès');
      setOldPassword('');
      setNewPassword('');
      setConfirmPassword('');
    } catch (error: any) {
      toast.error(error.response?.data?.message || 'Erreur lors du changement de mot de passe');
    } finally {
      setIsChangingPassword(false);
    }
  };

  const handleChangeEmail = (e: React.FormEvent) => {
    e.preventDefault();
    alert(`Email changé: ${email}`);
  };

  const handleDeleteAccount = () => {
    if (confirm('Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.')) {
      alert('Compte supprimé');
    }
  };

  return (
    <div className="space-y-8 max-w-3xl">
      <div>
        <h1 className="text-heading-1 text-white mb-2">Paramètres</h1>
        <p className="text-text-secondary text-body">
          Gérez vos paramètres de compte
        </p>
      </div>

      {/* Changement de mot de passe — comptes email/mdp uniquement. */}
      {hasRealEmail && (
        <Card className="glass-card">
          <CardHeader>
            <CardTitle className="text-heading-3 text-white flex items-center gap-2">
              <SettingsIcon className="w-5 h-5 text-cyan-neon" />
              Changer le mot de passe
            </CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleChangePassword} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="oldPassword" className="text-text-secondary">
                  Ancien mot de passe
                </Label>
                <Input
                  id="oldPassword"
                  type="password"
                  value={oldPassword}
                  onChange={(e) => setOldPassword(e.target.value)}
                  disabled={isChangingPassword}
                  autoComplete="current-password"
                  className="bg-dark-blue-lighter border-glass-border text-white"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="newPassword" className="text-text-secondary">
                  Nouveau mot de passe
                </Label>
                <Input
                  id="newPassword"
                  type="password"
                  value={newPassword}
                  onChange={(e) => setNewPassword(e.target.value)}
                  disabled={isChangingPassword}
                  autoComplete="new-password"
                  placeholder="Au moins 8 caractères"
                  className="bg-dark-blue-lighter border-glass-border text-white"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmPassword" className="text-text-secondary">
                  Confirmer le mot de passe
                </Label>
                <Input
                  id="confirmPassword"
                  type="password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  disabled={isChangingPassword}
                  autoComplete="new-password"
                  className="bg-dark-blue-lighter border-glass-border text-white"
                />
              </div>

              <div className="flex gap-3">
                <Button type="submit" disabled={isChangingPassword} className="glass-button">
                  {isChangingPassword ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Enregistrement...
                    </>
                  ) : (
                    'Sauvegarder'
                  )}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  disabled={isChangingPassword}
                  onClick={() => {
                    setOldPassword('');
                    setNewPassword('');
                    setConfirmPassword('');
                  }}
                  className="border-glass-border text-text-secondary hover:text-white hover:bg-glass-surface/50"
                >
                  Annuler
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      )}

      {/* Section email — affichage différent selon si l'utilisateur a un vrai email ou un email auto-généré (compte wallet). */}
      {hasRealEmail ? (
        <>
          {/* Vérification d'email — uniquement pour les vrais emails. */}
          <Card className="glass-card">
            <CardHeader>
              <CardTitle className="text-heading-3 text-white flex items-center gap-2">
                <Mail className="w-5 h-5 text-cyan-neon" />
                Verification Email
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white font-medium">{user?.email}</p>
                  <p className="text-text-muted text-sm">Votre adresse email</p>
                </div>
                {isLoadingStatus ? (
                  <Loader2 className="w-5 h-5 text-cyan-neon animate-spin" />
                ) : isEmailVerified ? (
                  <Badge className="bg-success/20 text-success border-success/30 flex items-center gap-1">
                    <CheckCircle className="w-3 h-3" />
                    Verifie
                  </Badge>
                ) : (
                  <Badge className="bg-warning/20 text-warning border-warning/30 flex items-center gap-1">
                    <XCircle className="w-3 h-3" />
                    Non verifie
                  </Badge>
                )}
              </div>

              {!isEmailVerified && !isLoadingStatus && (
                <div className="pt-2">
                  <Button
                    onClick={handleSendVerification}
                    disabled={isSendingVerification}
                    className="glass-button gap-2"
                  >
                    {isSendingVerification ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Envoi en cours...
                      </>
                    ) : (
                      <>
                        <Send className="w-4 h-4" />
                        Envoyer email de verification
                      </>
                    )}
                  </Button>
                  <p className="text-text-muted text-xs mt-2">
                    Un email de verification sera envoye a votre adresse.
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Modification d'email. */}
          <Card className="glass-card">
            <CardHeader>
              <CardTitle className="text-heading-3 text-white">
                Changer l'email
              </CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleChangeEmail} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="email" className="text-text-secondary">
                    Nouvelle adresse email
                  </Label>
                  <Input
                    id="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="votre@email.com"
                    className="bg-dark-blue-lighter border-glass-border text-white"
                  />
                </div>

                <Button type="submit" className="glass-button">
                  Mettre a jour
                </Button>
              </form>
            </CardContent>
          </Card>
        </>
      ) : (
        /* Ajout d'email — uniquement pour les comptes wallet sans vrai email. */
        <Card className="glass-card border-cyan-neon/30">
          <CardHeader>
            <CardTitle className="text-heading-3 text-white flex items-center gap-2">
              <Mail className="w-5 h-5 text-cyan-neon" />
              Ajouter votre email
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-text-secondary text-sm mb-4">
              Ajoutez une adresse email pour recevoir des notifications et securiser votre compte.
            </p>
            <form onSubmit={handleChangeEmail} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email" className="text-text-secondary">
                  Adresse email
                </Label>
                <Input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="votre@email.com"
                  className="bg-dark-blue-lighter border-glass-border text-white"
                />
              </div>

              <Button type="submit" className="glass-button gap-2">
                <Plus className="w-4 h-4" />
                Ajouter l'email
              </Button>
            </form>
          </CardContent>
        </Card>
      )}

      <Separator className="bg-glass-border" />

      {/* Zone de danger : suppression du compte. */}
      <Card className="glass-card border-error/30">
        <CardHeader>
          <CardTitle className="text-heading-3 text-error">
            Zone de danger
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-text-secondary text-body-sm">
            La suppression de votre compte est permanente et irréversible. Tous vos documents et fonds verrouillés seront perdus.
          </p>
          <Button
            onClick={handleDeleteAccount}
            variant="destructive"
            className="bg-error/20 text-error border border-error/30 hover:bg-error/30"
          >
            Supprimer le compte
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}